In [1]:
import pandas as pd
import numpy as np
from sklearn import datasets
import researchpy as rp
import statsmodels.api as sm
from statsmodels.formula.api import ols
import statsmodels.stats.multicomp

In [2]:
file = 'source_data/zumacin_scrubbed.csv'

In [3]:
df = pd.read_csv(file, encoding="ISO-8859-1")

In [4]:
df.head(5)

,SAMPLE_NUMBER,Assay Date,Compartment Temp,Reagent-A ID,Reagent-A ID Exp Date,Reagent-B Exp Date,Reagent-B ID,Material-A ID,Reagent-C Lot,Reagent-D Lot,Reagent-E Lot,Reagent-F Concentration,Reagent-F Expiration,Reagent-F Lot,SOP Version,Agg%,INSTRUMENT,Main%,Lab_Site,Chemist
0,120629,01/28/2011,4.9,11-001-0014,04/25/2011,NaN,NaN,R5307-19P,NaN,NaN,10R1856,NaN,01/31/2012,0R1860,4.0,5.790,27.0,90.430,Stat,ChemistO
1,126733,02/15/2011,4.9,11R0834,05/12/2011,02/23/2011,11R1008,P5530-19N,NaN,NaN,10R1856,NaN,01/31/2012,0R1860,4.0,5.980,81.0,90.160,Park,ChemistV
2,134380,03/04/2011,5.2,11-001-0014,04/25/2011,NaN,NaN,R6269-22P,NaN,NaN,11-005-0006,NaN,01/31/2012,0R1860,4.0,5.811,34.0,90.301,Stat,ChemistO
3,140369,03/23/2011,4.9,11R1229,06/14/2011,03/30/2011,11R0847,P5530-19N,NaN,NaN,10R1856,NaN,01/31/2012,0R1860,4.0,5.940,50.0,90.202,Park,ChemistV
4,142003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df.groupby(['Reagent-F Lot']).count()

,SAMPLE_NUMBER,Assay Date,Compartment Temp,Reagent-A ID,Reagent-A ID Exp Date,Reagent-B Exp Date,Reagent-B ID,Material-A ID,Reagent-C Lot,Reagent-D Lot,Reagent-E Lot,Reagent-F Concentration,Reagent-F Expiration,SOP Version,Agg%,INSTRUMENT,Main%,Lab_Site,Chemist
Reagent-F Lot,,,,,,,,,,,,,,,,,,,
001,95,95,91,95,95,0,0,95,0,95,95,95,95,95,91,95,91,95,95
0R1860,133,133,121,133,133,17,17,132,116,121,133,121,133,132,119,133,122,133,133
3-039-0106,188,188,186,187,187,0,0,184,0,187,177,188,188,188,147,188,149,188,188

In [6]:
df['Reagent-C Lot'].unique()

array([nan, 'C100', 'C200'], dtype=object)

Items to include in the analysis:
- Reagent-F lot
- Compartment Temp
- Reagent-A ID
- Material-A ID
- Reagent-D Lot
- SOP Version
- INSTRUMENT
- Lab_Site
- Chemist

In [7]:
an_df = df[['Reagent-F Lot', 'Compartment Temp', 'Reagent-A ID', 'Material-A ID', 'Reagent-D Lot', 'SOP Version', 'INSTRUMENT',
           'Lab_Site', 'Chemist','Agg%','Main%']]

In [8]:
an_df.head()

,Reagent-F Lot,Compartment Temp,Reagent-A ID,Material-A ID,Reagent-D Lot,SOP Version,INSTRUMENT,Lab_Site,Chemist,Agg%,Main%
0,0R1860,4.9,11-001-0014,R5307-19P,NaN,4.0,27.0,Stat,ChemistO,5.790,90.430
1,0R1860,4.9,11R0834,P5530-19N,NaN,4.0,81.0,Park,ChemistV,5.980,90.160
2,0R1860,5.2,11-001-0014,R6269-22P,NaN,4.0,34.0,Stat,ChemistO,5.811,90.301
3,0R1860,4.9,11R1229,P5530-19N,NaN,4.0,50.0,Park,ChemistV,5.940,90.202
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
final_df = an_df.dropna(how='any')

In [10]:
final_df.rename(columns={'Agg%':'Agg'}, inplace=True)

C:\Users\Lenovo\Anaconda3\lib\site-packages\pandas\core\frame.py:3781: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)

In [11]:
final_df.head()

,Reagent-F Lot,Compartment Temp,Reagent-A ID,Material-A ID,Reagent-D Lot,SOP Version,INSTRUMENT,Lab_Site,Chemist,Agg,Main%
17,0R1860,4.9,11-015-0052,R6284-22P,11-014-0044,5.0,29.0,Stat,ChemistB,6.1335,89.6405
19,0R1860,4.9,11-014-0076,R6284-22P,11-014-0044,5.0,26.0,Stat,ChemistB,6.0035,89.8070
24,0R1860,5.2,11R1271,S4165-09P,11R1525,5.0,80.0,Park,ChemistW,5.9065,90.0530
25,0R1860,4.9,11-016-0112,R6284-22P,11-014-0125,5.0,26.0,Stat,ChemistB,5.9560,89.9190
26,0R1860,4.9,11-015-0173,R6284-22P,11-014-0125,5.0,26.0,Stat,ChemistO,5.9015,89.9900

In [12]:
final_df.groupby(['Reagent-F Lot']).count()

,Compartment Temp,Reagent-A ID,Material-A ID,Reagent-D Lot,SOP Version,INSTRUMENT,Lab_Site,Chemist,Agg,Main%
Reagent-F Lot,,,,,,,,,,
001,87,87,87,87,87,87,87,87,87,87
0R1860,99,99,99,99,99,99,99,99,99,99
3-039-0106,144,144,144,144,144,144,144,144,144,144

In [13]:
final_df.reset_index(drop=True, inplace=True)

In [14]:
final_scrubbed = final_df.replace({'001': 'F-lot-1', '0R1860': 'F-lot-2', '3-039-0106': 'F-lot-3'})

In [15]:
final_scrubbed.head()

,Reagent-F Lot,Compartment Temp,Reagent-A ID,Material-A ID,Reagent-D Lot,SOP Version,INSTRUMENT,Lab_Site,Chemist,Agg,Main%
0,F-lot-2,4.9,11-015-0052,R6284-22P,11-014-0044,5.0,29.0,Stat,ChemistB,6.1335,89.6405
1,F-lot-2,4.9,11-014-0076,R6284-22P,11-014-0044,5.0,26.0,Stat,ChemistB,6.0035,89.8070
2,F-lot-2,5.2,11R1271,S4165-09P,11R1525,5.0,80.0,Park,ChemistW,5.9065,90.0530
3,F-lot-2,4.9,11-016-0112,R6284-22P,11-014-0125,5.0,26.0,Stat,ChemistB,5.9560,89.9190
4,F-lot-2,4.9,11-015-0173,R6284-22P,11-014-0125,5.0,26.0,Stat,ChemistO,5.9015,89.9900

In [16]:
rp.summary_cont(final_df['Agg'])

  Variable      N      Mean        SD        SE  95% Conf.  Interval
0      Agg  330.0  3.502762  1.655145  0.091113   3.323525  3.681999

In [17]:
rp.summary_cont(final_df.groupby(['Lab_Site']))['Agg']

            N      Mean        SD        SE  95% Conf.  Interval
Lab_Site
LIN        81  2.510891  0.374008  0.041556   2.429441  2.592342
Park       12  6.048744  0.180126  0.051998   5.946828  6.150660
Stat      237  3.712845  1.748871  0.113601   3.490186  3.935504

In [18]:
rp.summary_cont(final_df.groupby(['Reagent-F Lot', 'Lab_Site']))['Agg']

                         N      Mean        SD        SE  95% Conf.  Interval
Reagent-F Lot Lab_Site
001           LIN       35  2.916860  0.041317  0.006984   2.903171  2.930548
              Stat      52  2.917987  0.053777  0.007457   2.903370  2.932603
0R1860        Park      12  6.048744  0.180126  0.051998   5.946828  6.150660
              Stat      87  5.960584  0.241693  0.025912   5.909796  6.011372
3-039-0106    LIN       46  2.202002  0.147208  0.021705   2.159461  2.244543
              Stat      98  2.139165  0.126242  0.012752   2.114170  2.164160

In [49]:
final_scrubbed.rename(columns={'Reagent-F Lot':'ReagentF'}, inplace=True)

In [50]:
final_scrubbed.head()

,ReagentF,Compartment Temp,Reagent-A ID,Material-A ID,Reagent-D Lot,SOP Version,INSTRUMENT,Lab_Site,Chemist,Agg,Main%
0,F-lot-2,4.9,11-015-0052,R6284-22P,11-014-0044,5.0,29.0,Stat,ChemistB,6.1335,89.6405
1,F-lot-2,4.9,11-014-0076,R6284-22P,11-014-0044,5.0,26.0,Stat,ChemistB,6.0035,89.8070
2,F-lot-2,5.2,11R1271,S4165-09P,11R1525,5.0,80.0,Park,ChemistW,5.9065,90.0530
3,F-lot-2,4.9,11-016-0112,R6284-22P,11-014-0125,5.0,26.0,Stat,ChemistB,5.9560,89.9190
4,F-lot-2,4.9,11-015-0173,R6284-22P,11-014-0125,5.0,26.0,Stat,ChemistO,5.9015,89.9900

In [57]:
final_scrubbed['INSTRUMENT'] = final_scrubbed['INSTRUMENT'].astype(str)

In [68]:
model2 = ols('Agg ~ C(ReagentF)+ C(Lab_Site + Chemist)', final_scrubbed).fit()

print(f"Overall model F({model2.df_model: .0f},{model2.df_resid: .0f}) = {model2.fvalue: .3f}, p = {model2.f_pvalue: .4f}")

Overall model F( 22, 307) =  1708.787, p =  0.0000

In [69]:
model2.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                    Agg   R-squared:                       0.992
Model:                            OLS   Adj. R-squared:                  0.991
Method:                 Least Squares   F-statistic:                     1709.
Date:                Sun, 05 May 2019   Prob (F-statistic):          2.36e-306
Time:                        23:20:15   Log-Likelihood:                 160.59
No. Observations:                 330   AIC:                            -275.2
Df Residuals:                     307   BIC:                            -187.8
Df Model:                          22
Covariance Type:            nonrobust
=========================================================================================================
                                            coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------------------
Intercept                                 2.9791      0.046     65.195      0.000       2.889       3.069
C(ReagentF)[T.F-lot-2]                    3.0449      0.033     92.131      0.000       2.980       3.110
C(ReagentF)[T.F-lot-3]                   -0.7722      0.028    -27.886      0.000      -0.827      -0.718
C(Lab_Site + Chemist)[T.LINChemistJ]      0.0839      0.115      0.730      0.466      -0.142       0.310
C(Lab_Site + Chemist)[T.LINChemistK]      0.0338      0.061      0.556      0.578      -0.086       0.154
C(Lab_Site + Chemist)[T.LINChemistM]     -0.1481      0.078     -1.899      0.058      -0.301       0.005
C(Lab_Site + Chemist)[T.LINChemistN]     -0.0430      0.049     -0.869      0.386      -0.140       0.054
C(Lab_Site + Chemist)[T.LINChemistR]     -0.0355      0.075     -0.473      0.636      -0.183       0.112
C(Lab_Site + Chemist)[T.LINChemistS]     -0.0765      0.074     -1.032      0.303      -0.222       0.069
C(Lab_Site + Chemist)[T.ParkChemistA]     0.1372      0.100      1.377      0.170      -0.059       0.333
C(Lab_Site + Chemist)[T.ParkChemistF]     0.0033      0.077      0.043      0.966      -0.149       0.155
C(Lab_Site + Chemist)[T.ParkChemistP]    -0.0081      0.118     -0.069      0.945      -0.240       0.224
C(Lab_Site + Chemist)[T.ParkChemistW]    -0.1174      0.161     -0.731      0.465      -0.433       0.199
C(Lab_Site + Chemist)[T.StatChemistB]    -0.0631      0.046     -1.374      0.170      -0.154       0.027
C(Lab_Site + Chemist)[T.StatChemistC]     0.1127      0.077      1.459      0.146      -0.039       0.265
C(Lab_Site + Chemist)[T.StatChemistD]    -0.1503      0.074     -2.044      0.042      -0.295      -0.006
C(Lab_Site + Chemist)[T.StatChemistE]    -0.0763      0.042     -1.810      0.071      -0.159       0.007
C(Lab_Site + Chemist)[T.StatChemistG]    -0.0030      0.044     -0.068      0.946      -0.090       0.084
C(Lab_Site + Chemist)[T.StatChemistL]    -0.1009      0.047     -2.143      0.033      -0.194      -0.008
C(Lab_Site + Chemist)[T.StatChemistO]    -0.1567      0.058     -2.682      0.008      -0.272      -0.042
C(Lab_Site + Chemist)[T.StatChemistQ]    -0.1667      0.115     -1.450      0.148      -0.393       0.059
C(Lab_Site + Chemist)[T.StatChemistT]    -0.0325      0.064     -0.509      0.611      -0.158       0.093
C(Lab_Site + Chemist)[T.StatChemistU]    -0.0956      0.074     -1.290      0.198      -0.241       0.050
==============================================================================
Omnibus:                       47.827   Durbin-Watson:                   1.508
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              194.267
Skew:                          -0.526   Prob(JB):                     6.54e-43
Kurtosis:                       6.608   Cond. No.                         27.7
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

The Durban-Watson test is to detect the presence of autocorrelation, Jarque-Bera tests the assumption of normality, Omnibus tests the assumption of homogeneity of variance, and the Condition Number assess multicollinearity. Condition Number values over 20 are indicative of multicollinearity.

In [70]:
results = sm.stats.anova_lm(model2, typ= 2)
results

                           sum_sq     df             F         PR(>F)
C(ReagentF)            505.751856    2.0  10633.645376  3.284609e-284
C(Lab_Site + Chemist)    1.012109   20.0      2.128002   3.718523e-03
Residual                 7.300686  307.0           NaN            NaN

In [108]:
model3 = ols('Agg ~ C(ReagentF)+ C(Lab_Site + Chemist) + INSTRUMENT', final_scrubbed).fit()

print(f"Overall model F({model2.df_model: .0f},{model2.df_resid: .0f}) = {model2.fvalue: .3f}, p = {model2.f_pvalue: .4f}")

Overall model F( 22, 307) =  1708.787, p =  0.0000

In [109]:
model3.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                    Agg   R-squared:                       0.992
Model:                            OLS   Adj. R-squared:                  0.991
Method:                 Least Squares   F-statistic:                     713.0
Date:                Sun, 05 May 2019   Prob (F-statistic):          1.54e-266
Time:                        23:44:40   Log-Likelihood:                 171.38
No. Observations:                 330   AIC:                            -238.8
Df Residuals:                     278   BIC:                            -41.20
Df Model:                          51
Covariance Type:            nonrobust
=========================================================================================================
                                            coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------------------
Intercept                                 3.0078      0.130     23.155      0.000       2.752       3.264
C(ReagentF)[T.F-lot-2]                    3.0259      0.039     76.691      0.000       2.948       3.104
C(ReagentF)[T.F-lot-3]                   -0.8036      0.034    -23.738      0.000      -0.870      -0.737
C(Lab_Site + Chemist)[T.LINChemistJ]      0.0701      0.162      0.434      0.665      -0.248       0.389
C(Lab_Site + Chemist)[T.LINChemistK]      0.0434      0.071      0.608      0.543      -0.097       0.184
C(Lab_Site + Chemist)[T.LINChemistM]     -0.1469      0.081     -1.809      0.072      -0.307       0.013
C(Lab_Site + Chemist)[T.LINChemistN]     -0.0534      0.061     -0.870      0.385      -0.174       0.067
C(Lab_Site + Chemist)[T.LINChemistR]     -0.0421      0.092     -0.457      0.648      -0.223       0.139
C(Lab_Site + Chemist)[T.LINChemistS]     -0.1055      0.098     -1.079      0.282      -0.298       0.087
C(Lab_Site + Chemist)[T.ParkChemistA]     0.0960      0.151      0.637      0.525      -0.201       0.393
C(Lab_Site + Chemist)[T.ParkChemistF]     0.0532      0.117      0.456      0.649      -0.176       0.283
C(Lab_Site + Chemist)[T.ParkChemistP]     0.0305      0.144      0.212      0.832      -0.252       0.313
C(Lab_Site + Chemist)[T.ParkChemistW]    -0.1701      0.197     -0.863      0.389      -0.558       0.218
C(Lab_Site + Chemist)[T.StatChemistB]    -0.0594      0.081     -0.729      0.467      -0.220       0.101
C(Lab_Site + Chemist)[T.StatChemistC]     0.1667      0.102      1.627      0.105      -0.035       0.368
C(Lab_Site + Chemist)[T.StatChemistD]    -0.1314      0.099     -1.323      0.187      -0.327       0.064
C(Lab_Site + Chemist)[T.StatChemistE]    -0.0575      0.080     -0.721      0.472      -0.215       0.100
C(Lab_Site + Chemist)[T.StatChemistG]     0.0084      0.082      0.103      0.918      -0.152       0.169
C(Lab_Site + Chemist)[T.StatChemistL]    -0.0946      0.083     -1.139      0.256      -0.258       0.069
C(Lab_Site + Chemist)[T.StatChemistO]    -0.1335      0.089     -1.499      0.135      -0.309       0.042
C(Lab_Site + Chemist)[T.StatChemistQ]    -0.1193      0.137     -0.872      0.384      -0.389       0.150
C(Lab_Site + Chemist)[T.StatChemistT]    -0.0160      0.094     -0.170      0.865      -0.202       0.170
C(Lab_Site + Chemist)[T.StatChemistU]    -0.0921      0.099     -0.926      0.355      -0.288       0.104
INSTRUMENT[T.18.0]                       -0.0343      0.132     -0.260      0.795      -0.294       0.225
INSTRUMENT[T.183.0]                       0.0350      0.130      0.270      0.788      -0.221       0.291
INSTRUMENT[T.184.0]                      -0.0200      0.121     -0.165      0.869      -0.258       0.218
INSTRUMENT[T.25.0]                       -0.2677      0.124     -2.151      0.032      -0.513      -0.023
INSTRUMENT[T.26.0]                        0.0326      0.064      0.507      0.612      -0.094       0.159
INSTRUMENT[T.263.0]                       0.1031      0.168      0.612      0.541      -0.229       0.435
INSTRUMENT[T.27.0]                       -0.0333      0.090     -0.371      0.711      -0.210       0.144
INSTRUMENT[T.28.0]                       -0.0449      0.059     -0.766      0.444      -0.160       0.070
INSTRUMENT[T.29.0]                       -0.0202      0.061     -0.334      0.739      -0.139       0.099
INSTRUMENT[T.30.0]                        0.0473      0.162      0.292      0.771      -0.272       0.367
INSTRUMENT[T.34.0]                       -0.0617      0.064     -0.970      0.333      -0.187       0.064
INSTRUMENT[T.36.0]                       -0.0877      0.128     -0.684      0.495      -0.340       0.165
INSTRUMENT[T.361.0]                       0.0496      0.189      0.263      0.793      -0.322       0.421
INSTRUMENT[T.362.0]                      -0.0166      0.169     -0.099      0.922      -0.349       0.316
INSTRUMENT[T.37.0]                       -0.0141      0.077     -0.184      0.854      -0.165       0.137
INSTRUMENT[T.38.0]                       -0.0171      0.067     -0.256      0.798      -0.149       0.114
INSTRUMENT[T.381.0]                      -0.0778      0.197     -0.394      0.694      -0.467       0.311
INSTRUMENT[T.39.0]                        0.0003      0.076      0.004      0.997      -0.149       0.149
INSTRUMENT[T.40.0]                       -0.0447      0.064     -0.702      0.484      -0.170       0.081
INSTRUMENT[T.406.0]                       0.0208      0.150      0.138      0.890      -0.275       0.317
INSTRUMENT[T.408.0]                      -0.0621      0.142     -0.438      0.662      -0.341       0.217
INSTRUMENT[T.41.0]                       -0.0064      0.059     -0.108      0.914      -0.123       0.110
INSTRUMENT[T.42.0]                       -0.0288      0.072     -0.400      0.689      -0.170       0.113
INSTRUMENT[T.43.0]                        0.0178      0.064      0.280      0.780      -0.107       0.143
INSTRUMENT[T.437.0]                       0.0877      0.146      0.600      0.549      -0.200       0.375
INSTRUMENT[T.47.0]                       -0.1343      0.173     -0.777      0.438      -0.475       0.206
INSTRUMENT[T.48.0]                        0.0588      0.198      0.298      0.766      -0.330       0.448
INSTRUMENT[T.69.0]                        0.1753      0.198      0.888      0.375      -0.213       0.564
INSTRUMENT[T.71.0]                        0.0065      0.142      0.046      0.964      -0.272       0.285
INSTRUMENT[T.80.0]                        0.0429      0.126      0.341      0.733      -0.205       0.290
INSTRUMENT[T.81.0]                       -0.1397      0.097     -1.434      0.153      -0.331       0.052
==============================================================================
Omnibus:                       45.957   Durbin-Watson:                   1.611
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              188.556
Skew:                          -0.494   Prob(JB):                     1.14e-41
Kurtosis:                       6.569   Cond. No.                     1.24e+16
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 3.2e-30. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [110]:
results3 = sm.stats.anova_lm(model3, typ= 2)
results3

                           sum_sq     df            F         PR(>F)
C(ReagentF)            347.656794    2.0  7066.581402  4.603225e-239
C(Lab_Site + Chemist)    0.918977   20.0     1.867942   1.469365e-02
INSTRUMENT               0.566278   31.0     0.742603   8.398334e-01
Residual                 6.838426  278.0          NaN            NaN

In [ ]:
cols = list(final_df.columns)